generate local certificates
modell-aachen/modac-dev-machine-setup pull request #19
Opened 2021-07-22 12:15 UTC by kaiivoschneider

2021-07-22 12:23 UTC, quitejonny requested changes

2021-07-22 12:23 UTC, quitejonny commented on provisioning/tasks/certificates/generate_certificate.yml
> +---
mit ansible modul

2021-08-02 08:36 UTC, mmoscher requested changes

2021-08-02 08:36 UTC, mmoscher commented on provisioning/tasks/certificates/generate_certificate.yml
> +  command: "mv ./{{ host }}.pem {{ location }}"
```suggestion
  command: "mv ./{{ host }}.pem {{ location }}"
```

copy mit remote_src, ggf danach die quelldatei löschen

2021-08-02 08:36 UTC, mmoscher commented on provisioning/tasks/certificates/generate_certificate.yml
> +  command: "mv ./{{ host }}-key.pem {{ location }}"
copy mit remote_src, ggf danach die quelldatei löschen

2021-08-02 08:36 UTC, mmoscher commented on provisioning/tasks/certificates/generate_certificate.yml
> +  command: "mkcert {{ host }}"
ggf auch hier CAROOT setzen, sieht unten

2021-08-02 09:18 UTC, mmoscher requested changes

2021-08-02 09:18 UTC, mmoscher commented on provisioning/tasks/generate_certificates.yml
> +    CAROOT: "{{ all_env['QWIKI_DEVELOPMENT_ROOT_CA'] }}"
weiß du ob der pfad anlegt wird? Ansonsten bräuchten wir hiervor noch die Erstellung des Ordners.

2021-08-02 09:20 UTC, mmoscher approved these changes

2021-08-02 09:21 UTC, merged