MAC support
modell-aachen/modac-dev-machine-setup pull request #34
Opened 2022-03-24 14:33 UTC by mmoscher

2022-03-24 15:14 UTC, kaiivoschneider requested changes

2022-03-24 15:14 UTC, kaiivoschneider commented on provisioning/tasks/install/Debian/x86_64/certificates.yml
> +- stat:
Dopplung zwischen darwin und debian

2022-03-24 15:14 UTC, kaiivoschneider commented on provisioning/tasks/install_packages.yml
> +- name: Install packages on Mac.
```suggestion
- name: Install packages on Darwin.
```

2022-03-24 15:14 UTC, kaiivoschneider commented on provisioning/tasks/install_packages.yml
> +        name: "{{ all_packages }}"
```suggestion
        name: "{{ all_packages_debian }}"
```

2022-03-24 15:14 UTC, kaiivoschneider commented on provisioning/tasks/install_packages.yml
> +      loop: "{{ all_packages_mac }}"
```suggestion
      loop: "{{ all_packages_darwin }}"
```

2022-03-24 15:14 UTC, kaiivoschneider commented on provisioning/tasks/remove_packages.yml
> +      loop: "{{ all_remove_packages_mac }}"
```suggestion
      loop: "{{ all_remove_packages_darwin }}"
```

2022-03-24 15:14 UTC, kaiivoschneider commented on provisioning/tasks/remove_packages.yml
> +        name: "{{ all_remove_packages }}"
```suggestion
        name: "{{ all_remove_packages_debian }}"
```

2022-03-24 15:14 UTC, kaiivoschneider commented on provisioning/tasks/remove_packages.yml
> +- name: Remove packages on Mac.
```suggestion
- name: Remove packages on Darwin.
```

2022-03-24 15:24 UTC, mmoscher commented on provisioning/tasks/install/Debian/x86_64/certificates.yml
> +- stat:
Gerade leider nicht wirklich anders möglich
ich würde die Ordnerstrukturen künftig eh gerne wieder abschaffen, denn das iterieren und schauen ob Dateien da sind gefällt mir noch nicht so.
ggf machen wir auch nen ganz eigenes playbook für mac, mal schauen.

2022-03-24 15:27 UTC, kaiivoschneider approved these changes

2022-04-04 08:46 UTC, mmoscher commented on provisioning/tasks/remove_packages.yml
> +    - name: Ensure common packages are installed.
```suggestion
    - name: Ensure unwanted packages are removed.
```

2022-04-04 09:23 UTC, kaiivoschneider approved these changes

2022-04-04 13:11 UTC, merged