adds arm64 (macos m1) provisioning
modell-aachen/modac-dev-machine-setup pull request #53
Opened 2022-11-16 09:11 UTC by mmoscher

2022-11-16 09:23 UTC, mmoscher commented on provisioning/requirements.yml
> +  - name: geerlingguy.mac
```suggestion
  - name: geerlingguy.mac

```

2022-11-16 09:23 UTC, mmoscher commented on provisioning/tasks/configure/Darwin/dnsmasq.yaml
> +          content: "nameserver 127.0.0.1"
```suggestion
          content: "nameserver 127.0.0.1"

```

2022-11-16 09:23 UTC, mmoscher commented on provisioning/tasks/setup_modac_bash.yml
> +  when: configure_shell_rc
```suggestion
  when: configure_shell_rc

```

2022-11-16 14:02 UTC, PB1994 requested changes

2022-11-16 14:02 UTC, PB1994 commented on provisioning/vars/main.yml
> +    # - terragrunt # not yet available for mac
müssen wir noch umziehn

2022-11-18 07:55 UTC, mmoscher commented on provisioning/vars/main.yml
> +    # - terragrunt # not yet available for mac
done

2022-11-21 10:02 UTC, PB1994 approved these changes

2022-11-21 12:07 UTC, merged